### ISSUE TITLE
Customize Toolbar breakage with Pocket disabled

### ISSUE THREAD

**Issue by mimecry** [aminomancer/uc.css.js#10]
Hey, i found this bug while trying to incorporate my user.js from my current setup into your theme. If i set the following in my user.js

`user_pref("extensions.pocket.enabled", false`;

when i try to use the Customize toolbar function, instead of this

![image](https://user-images.githubusercontent.com/10742312/128003869-ff490d76-12f2-4cbe-a6a5-8587584f20e6.png)

it will result in this 

![image](https://user-images.githubusercontent.com/10742312/128003669-1b932273-1aac-4c95-b15f-473e43babf91.png)

and when i close the Customize Toolbar mode, the navbar will look like this

![image](https://user-images.githubusercontent.com/10742312/128003748-87c4b6ee-db20-48be-b2d9-5172fa29502c.png)

**Comment by aminomancer** [comment]
weird, I can't reproduce it. looks like you're missing a parentheses in that user_pref call? what operating system is this?

**Comment by aminomancer** [comment]
you sure you don't have an old/deprecated script installed somewhere? make sure you don't have any scripts that aren't currently in the repo. others have complained and posted similar screenshots of the UI all messed up, and turned out to be using 6 month old scripts that I stopped developing.

**Comment by aminomancer** [comment]
also maybe you should check if you have any old custom prefs. search `userchrome.` in about:config and delete every preference you see

**Comment by aminomancer** [comment]
also can you show me a bigger screenshot? actually it'd be better if it was just a complete screen capture. your bug might be unique to your layout or general environment, and I can't fix it if I can't reproduce it. also, sending me the browser toolbox console log would be helpful too. the fact that something says `null` suggests there's a javascript error in here somewhere. which will be in the console. that would help narrow it down.

**Comment by mimecry** [comment]
all tests are conducted with a vanilla profile using your files downloaded from about 2 hours ago, so no worries of leftover files or configs having an effect. Win 10 x64  1909 (18363.418), same version as yours as you said last time iirc

full screen captures 

with your default user.js

![image](https://user-images.githubusercontent.com/10742312/128009448-e3c0d25a-c5c4-4c7a-9138-270512a3b123.png)

with the pocket pref added to user.js (before first run) 

![image](https://user-images.githubusercontent.com/10742312/128009763-7e934640-7993-4fb2-90ec-f42f8c17af6f.png)

![image](https://user-images.githubusercontent.com/10742312/128009260-3fa42cff-d814-41ed-9233-9618b6552e60.png)

browser console is empty in both cases

**Comment by mimecry** [comment]
oh sorry about that, i had the developer console opened instead of the browser console. also forgot to use nightly for my testing 😬 but result remains the same. i exported the two console outputs and attached them here since i can't fit them into a single screenshot

[console-export-normal.txt](https://github.com/aminomancer/uc.css.js/files/6924211/console-export-normal.txt)
[console-export-bug.txt](https://github.com/aminomancer/uc.css.js/files/6924210/console-export-bug.txt)

![image](https://user-images.githubusercontent.com/10742312/128019348-da5f244d-9ef0-4d10-9559-9d7d5a45628e.png)

**Comment by mimecry** [comment]
so the error does not happen if you first run the profile, then go to about:config and flip `extensions.pocket.enabled` to false. it only happens if you add it to user.js before the first run

**Comment by aminomancer** [comment]
yeah I tried with user.js. still could not reproduce the bug. maybe you should reinstall firefox and fx-autoconfig? could be issues with the profile too. how did you create this profile? check this out:
```
Could not get children of file(C:\Users\wtc\AppData\Roaming\Mozilla\Firefox\Profiles\lcmzo799.test bug\thumbnails) because it does not exist
```
why is it looking for thumbnails cache in your roaming folder? the thumbnails cache is in the *local* folder. this profile looks totally corrupted. if the profile was made recently and through normal means then maybe your entire firefox installation is broken. I don't know how else to explain this many error messages in the browser console. I mean, you can expect some errors, but I've never seen these types of errors in my life.

can you try deleting scripts one by one until the problem is gone? since you seem to have every script installed, and I can't reproduce the bug, I can't do anything but make a random guess. maybe the eyedropper button script, since it seems to go missing in your screenshots. or maybe the navbar toolbar slider script.

**Comment by aminomancer** [comment]
also, this is abnormal too
```
1627995179519	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1627995179519	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
```
these are definitely valid extension permissions, and the extension is built by mozilla. I don't see how this could happen unless your profile is corrupt or there's some mismatch between your firefox version and your profile. although even that doesn't really make sense bc the extension is built into firefox, not held in the profile.

**Comment by mimecry** [comment]
i created this profile by:

1. running firefox -p
2. create new profile using Profile Manager
3. copy user.js and chrome folder into profile directory, deleting all existing files if there are any
4. open FF using the newly created profile

will experiment some more tomorrow and see if i can figure out anything

**Comment by aminomancer** [comment]
did you run the profile once before copying everything into it?

**Comment by mimecry** [comment]
nah i mentioned above that i added everything to the profile folder before first run. is that poor practice?

**Comment by aminomancer** [comment]
well there's a lot of stuff that needs to happen during setup. all sorts of elements will be different or nonexistent. some global objects may not exist. before installing any scripts I would always run the profile and log into firefox account. then quit, install the javascript, and restart.

**Comment by aminomancer** [comment]
it's possible the scripts are causing a failure in the profile setup, corrupting the profile. you certainly don't want third-party code running while a profile or fxa account is being initialized. so yeah I think it would be wise to set up the profile and log into the fxa account beforehand.

**Comment by mimecry** [comment]
yep i can't replicate it i open the profile once before adding everything else to it. i'll make sure to do that from now on, i didn't consider what you said about third party code running during the initialization process. thanks for the help!

**Comment by aminomancer** [comment]
no problem. this stuff has been soaking up a lot of my time lately anyway. with so many scripts it's like playing whack-a-mole with new updates breaking things. now they changed the way favicons for closed tabs are cached and it broke the recently closed tabs/windows menus. which affects one of my scripts that puts an identical menu in the tab context menu. I fixed it but the fix only works in internal firefox scripts. if I apply the same fix to my script, it won't work because it'll create 2 different tab favicon maps.

I guess I gotta wait for them to upstream my fix, then completely redo my script so it uses the vanilla methods and fixes whatever they return after the fact. which I don't even think is practical so I might just have to throw the whole script out lol. this hobby is like drug addiction, if I knew how life-consuming the consequences would be, I'm not sure I'd have gotten into it in the first place

**Comment by mimecry** [comment]
lol i'm sure there are less healthy and more destructive habits out there.. would rebasing your stuff to a future stable version help reduce the amount of constant tinkering and fixing you have to do?
