### ISSUE TITLE
question about Auto-hide Navbar

### ISSUE THREAD

**Issue by DMITROSE** [aminomancer/uc.css.js#12]
Only one question:
userScripts is set to enable Auto-hide Navbar Support, 
but I have auto-hiding doesn't work, how to solve it

**Comment by aminomancer** [comment]
1. It requires using my CSS theme, or at least adding equivalent rules to your own. The script is not meant to implement auto-hiding, that's something you can do with pure CSS. The script is meant to prevent auto-hiding when popups are opened on the navbar. For example if you used just CSS, the navbar would expand when you hovered it, and then if you clicked the history toolbar button and moved your mouse down to the history popup panel, the navbar would collapse back. Because the history popup is not a child of the navbar, therefore when it's hovered, the navbar *isn't* hovered. It also stops the navbar from collapsing while the urlbar is focused. The script is the solution for these problems. It prevents navbar collapse while certain popups are opened or the urlbar is focused.
2. Like I said before, the script only prevents problems that arise from using CSS to auto-hide the navbar. It's the CSS theme (duskfox) that actually hides the navbar. And it only hides the navbar in fullscreen mode, like vanilla firefox does. It does auto-hide the bookmarks bar in normal/maximized mode though. And the bookmarks bar auto-hide system does use the support script. But the actual navbar auto-hide system is only enabled in fullscreen mode.
3. If you wanted to enable it in normal/maximized mode, you could go into [uc-fullscreen.css](/aminomancer/uc.css.js/blob/master/uc-fullscreen.css) and remove `[inFullscreen]` from the `:root` selector in all of the rules. Then those rules would apply all the time. I haven't tested that though, and wouldn't really recommend it. The theme wasn't designed to be one of those ultra-compact themes, it's mainly designed to maximize productivity on a 1440p to 2160p screen, and to be less harsh on the eyes. I only added the auto-hide navbar features because they're already present in vanilla firefox, they're just animated very poorly and they warp the content area's viewbox.

**Comment by DMITROSE** [comment]
Thank you for answering, I did not know about these nuances that you indicated above, I will take into account the recommendations. By the way, I not only put the theme on several of my machines as an example of yours, but also recommend that other users also install your themes on their FF.

**Comment by aminomancer** [comment]
> 
> 
> Thank you for answering, I did not know about these nuances that you indicated above, I will take into account the recommendations. By the way, I not only put the theme on several of my machines as an example of yours, but also recommend that other users also install your themes on their FF.

Thanks, good to know. good luck 👍
