### ISSUE TITLE
Tab sound button doesn't work in the vertical tab pane when the pane pinned

### ISSUE THREAD

**Issue by henryxrl** [aminomancer/uc.css.js#16]
The sound button (mute/unmute) does work in the vertical tab pane, just that when the pane is pinned (i.e., no expansion when during mouse hovering) it doesn't work any more.
![image](https://user-images.githubusercontent.com/7662954/140618742-934b4a39-6f5c-4bb3-92bc-bb83c3b48d4b.png)

**Comment by aminomancer** [comment]
It's not a button, it's just an overlay icon. Clicking it doesn't do anything. I used an icon instead of a button for several reasons. I figure if you want to mute/unmute you can just right click to open the context menu and click the button in there. Originally there were no buttons or icons in collapsed mode. I only added the overlay because I thought it was hard to find where the sound was coming from if there weren't any icons. I might look into other options in the future, but I don't think I'll just turn the icon into a button, because it's so easy to accidentally click when you're just trying to click the tab.
