### ISSUE TITLE
user.js:: I filled out all the "unrequired" about:config pref changes in user.js

### ISSUE THREAD

**Issue by KleinByte** [aminomancer/uc.css.js#22]
I think there should be two seperate user.js files. One with only required config changes and one with all of the config change recommendations.

Entering in all the about:config changes is tedious and time consuming. There may be some people who would like to just plug and play, like me when adding everything onto a new pc/os.

![image](https://user-images.githubusercontent.com/57239407/142051587-ca9c32c9-2801-4dda-8961-5405951eedb6.png)

I have the new user.js file if you'd like to just use that. I think the descriptions of all the changes could be added, but this is a start.

There would also need to be a disclaimer that the defaults are for windows, and users need to comment out and uncomment the correct lines for their os.

**Comment by KleinByte** [comment]
[user.txt](https://github.com/aminomancer/uc.css.js/files/7549251/user.txt)

I dont have push access so to quickly give you the file, the file was just changed to a txt file. Sorry if this is too sloppy.

**Comment by aminomancer** [comment]
Have you tried copying the prefs.js file? For some things it's usually best to just copy your entire profile, actually.

**Comment by aminomancer** [comment]
Alright the new prefs files are [in here](https://github.com/aminomancer/uc.css.js/tree/master/prefs). You can also just download the 3.0 release, the prefs files are packaged with it.

**Comment by KleinByte** [comment]
> 
> 
> Have you tried copying the prefs.js file? For some things it's usually best to just copy your entire profile, actually.

I see that now, thanks for the tip. Ill just copy my prefs file when moving to another system. Thanks

**Comment by aminomancer** [comment]
> 
> 
> > Have you tried copying the prefs.js file? For some things it's usually best to just copy your entire profile, actually.
> 
> I see that now, thanks for the tip. Ill just copy my prefs file when moving to another system. Thanks

Sure. Did you see the update? I added 2 versions of user.js file. I didn't put every pref, since I wasn't sure where to draw the line. The theme isn't really designed to have mandatory prefs and recommended prefs, it's mainly designed to have lots and lots of options. Maybe more than half the options I don't even use myself. And I have some controversial tastes maybe. So I wouldn't want to impose my more obscure preferences on the users. And there are also a lot of prefs that don't do anything unless you have a certain script installed. So I ended up just adding the prefs to recommended.js that I think are most important for creating the visual aesthetic seen in the screenshots.

I can see how that's not super helpful though. Maybe I can do 3 versions instead of 2. But it occurs to me that if the user disagrees with even just one of my prefs, that's enough to make the user.js files pretty much useless. Since it's faster for them to copy and paste their own user.js file than it is to copy mine, since they'd need to rename one of mine to user.js.

And there is good reason to change prefs via user.js instead of prefs.js. I tend to use prefs.js more because that's the one you control with about:config, and that's the one my scripts interface with when they call `Services.prefs.set*Pref`. Scripts can't change user.js directly as far as I know. But I wish I didn't do that, since I often lose prefs that way. Firefox doesn't alert you when it changes one of your prefs. You just randomly notice a month later that something's wrong and you have to spend an hour trying to figure out what it is. Sometimes the pref is obscure enough that you _never_ find out what it was before you feel the need to move on with your life.

So, basically if you're certain you want a pref to have a given value, as is likely the case with many prefs, it's better to set it with user.js since that file is protected from Normandy automatically changing your prefs when you update Firefox. If you're switching machines and you want to restore your profile in general, then you should just copy the entire profile over. Both prefs.js and user.js, along with literally everything else... the places DB, the session store, search.json.mozlz4, etc. These are all things I copy over when I restore a profile, because I indiscriminately copy the entire profile over.

On occasion I've been more discerning because the profile I was copying was really old and incompatible with new versions of Firefox. So I just did some trial & error, removing files from the backup payload until it worked without problems. I haven't had to do that in a long time though. Unfortunately some of the files that are most likely to cause a problem are prefs.js and user.js. So if you're backing up and restoring profiles a lot, you may occasionally have to delete prefs from those files one by one until Firefox doesn't crash on startup or something.

But yeah, by and large the common wisdom is to set important prefs with user.js, and some people whose opinion I trust suggest setting ALL your prefs with user.js. And it's fine to do that, because I rarely change any of the important prefs. After all, if their values were transitory or subject to change, they probably wouldn't be important. You can just check back on the repo every month or so to see if any new prefs have been added. Maybe in the prefs table, I'll add a note on the prefs that were added/changed within the last month so they're easier to find.

For all those reasons I think you'd be better off just backing up your own personal user.js file somewhere and copying that over when you switch profiles or computers.
