### ISSUE TITLE
Left and Right arrows should not change search engine when in url.

### ISSUE THREAD

**Issue by KleinByte** [aminomancer/uc.css.js#24]
**Describe the bug**

When switching to the searchbar, if I want to edit the current url by using the arrow-keys to navigate through the url, it does not move cursor locations.
Instead it switches between search engines. I believe this feature is supposed to only happen when using alt+arrow key if I read the readme properly.

**To Reproduce**
Go to any website i.e. youtube.com
Switch to the urlbar, the entire url should be highlighted, then use left or right arrow to navigate through url as if you were to change the url slightly.
Cursor shouldn't move, instead we cycle through the search engines.

**Expected behavior**
arrow keys should navigate through the url-address via moving cursor. ALT+arrow keys should navigate through search engines.

Thanks :)

**Comment by aminomancer** [comment]
No I think that's a misunderstanding. You're referring to oneClickOneOffSearchButtons.uc.js? That script just restores old firefox behavior. Not sure the version but the urlbar never had separate behavior for arrow keys vs. alt + arrow keys. Only the searchbar. The left/right arrow key behavior either always navigates through search engine one-off buttons, or always moves the input caret. The readme doesn't mention the alt key since the script does not handle key events at all, that's just the built-in urlbar input handler. Adding some kind of differential behavior on alt key could be an additional preference, but probably in the form of something separate, since that script's functions aren't aware of the event, so can't access `event.altKey`.

**Comment by KleinByte** [comment]
> 

Gotcha gotcha, I will disable this script then and that'll solve the problem. I personally don't see how removing the ability to navigate through urls with <> arrows would be something someone would want.
Thanks for explaining this.

**Comment by aminomancer** [comment]
You don't need to disable the whole script. You can just disable the preference `userChrome.urlbar.oneOffs.keyNavigation` in about:config. Yeah I don't use it or recommend it. That pref was made by request. The script isn't designed to mess with key navigation, it's designed to make clicking the one-off search engines immediately trigger a search with the clicked engine, instead of requiring the user to hit enter. Firefox used to have a pref that did that. It just happens that the pref was removed at the same time all the other browser.urlbar.update2 preferences were removed, which included the horizontal key navigation pref. So when I made the script, people asked me to restore the other removed prefs too. So I basically put things back the way they were before, albeit with custom pref names to avoid any conflict with firefox's internal prefs migration.
