### ISSUE TITLE
userChrome.css.mac-ui-fonts 

### ISSUE THREAD

**Issue by Mitezuss** [aminomancer/uc.css.js#25]
It is not a bug... just a question

How can i check if is working ? I did not see any effect (have installed all fonts) (i tried on fresh install)

Can give me some picture to compare ?

Thanks

**Comment by aminomancer** [comment]
There's a reason it says this lol
```
<!-- Please don't change or delete the template -->
```
What operating system? SF Pro is Apple's font so enabling this pref on macOS shouldn't have any significant effect. Might change the weights and stuff but the font is the same. If you're on Windows or Linux then show me a screenshot of something, I can identify the font.

You can easily tell whether it's working by opening the browser toolbox (Ctrl+Shift+Alt+i, or right-click my toolbox button if you have the script) to the "Style Editor" tab, find uc-misc.css, and delete line 480 where it says `font-family: SF Pro Text...`. If you have the font installed correctly, the font in your tabs and menus should immediately shift. If you don't, then you won't see any change since the `SF Pro Text` part will be ignored and it'll then proceed to `Segoe UI` then `sans-serif` in that order.

**Comment by aminomancer** [comment]
Did you download the fonts from Apple [directly](https://developer.apple.com/fonts/)? You need to download the .dmg file, and then if you're on windows, open it in 7-zip, and double click the .pkg file inside the archive, then double click `Payload~`, then `.`, then `Library`, then `Fonts`, then select all the fonts in there and drag and drop them to your desktop or something. Then select all of them, right click > Install. Or whatever the equivalent is on linux. Right now you only need to do this with SF Pro (the first one on the website, SF-Pro.dmg), but I may incorporate the other fonts in the future, and they're all really good fonts, so I recommend installing all 5 anyway.

**Comment by Mitezuss** [comment]
Hi, thank for the reply

Windows 7, firefox 94.0.2 (i have all settings good: UC, UCJS)

Downloaded from your link and are installed correctly. (https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg)

![0](https://user-images.githubusercontent.com/35956777/148249925-e96fc442-0dde-41bc-9686-f507261e9707.png)

@aminomancer 
_There's a reason it says this lol_

Sorry, i just wanna a pic showing me the "new" style (**maybe is a little change what i can not percive** (like the fonts on android, for example))

pd: sorry my english =d

**Comment by aminomancer** [comment]
If there's a problem with uc-misc.css then I need to know what it is so I can fix it

**Comment by Mitezuss** [comment]
@aminomancer 

Was a problem mine with the uc-misc.css, but your .css is working fine.

Regards.

PD: one extra question (:d just for know, i can not find info on google). is there a option like:

_@supports -moz-int-pref_

? maybe not =( (just bool -.-, should be cool have a int to choice)

**Comment by aminomancer** [comment]
I don't understand. You're editing uc-misc.css? Why? If you want to add custom rules you need to add them in custom-chrome.css, that's the only reason it exists. If you edit uc-misc.css then you're gonna lose your edits every time you update the stylesheet... and this theme gets updated almost every day.

No, -moz-bool-pref is a totally unique feature. It only works _because_ it's boolean. `@supports` is boolean so any function fed into it must be boolean too. It would be theoretically possible to implement something like `@supports -moz-string-pref("pref.name", "value")` but that would require changing how `@supports` works I think. Btw, you can answer those kinds of questions yourself by using [searchfox](https://searchfox.org/mozilla-central/search?q=-moz-int-pref).
