### ISSUE TITLE
TabPreview.uc.js

### ISSUE THREAD

**Issue by kaos-55** [aminomancer/uc.css.js#29]
Hi @aminomancer I recently found your repository and saw that it is possible to add some features to Firefox through javascripts (userchromejs). I am currently using the private tab script as there is no extension that provides such a feature.

Searching the web for a replacement for the tab scope extension that allows thumbnails on tabs I did not find anything similar. 
Is there a possibility that a script could be written to show thumbnails on tabs? If so, could this script I found on the web be ported to work with the latest version of Firefox?

[TabPreview.zip](https://github.com/aminomancer/uc.css.js/files/8046418/TabPreview.zip)

**Comment by aminomancer** [comment]
Sure, [does this](https://github.com/aminomancer/uc.css.js/blob/master/JS/tabThumbnailTooltip.uc.js) work for you?

**Comment by kaos-55** [comment]
Oh thank you so much.
I have been testing the script and I have noticed that in some pages that use long titles the thumbnail shows an empty space, I upload some examples. Besides that it works well.
![tabthumb](https://user-images.githubusercontent.com/86812371/153589803-22d72eef-adda-493c-9500-9188e347e2d8.png)
![tabthumb1](https://user-images.githubusercontent.com/86812371/153589805-903624f1-90e0-4849-8899-1862527e2d27.png)
![tabthumb2](https://user-images.githubusercontent.com/86812371/153589809-3df756fa-ecce-453d-b305-5dd68015b053.png)

**Comment by aminomancer** [comment]
So what do you think it should do instead? To avoid any empty space, I either need to 1) limit the max width of the label, making it wrap onto multiple lines or just overflow and terminate in a `...` ellipsis; or 2) unlimit the max height of the thumbnail, which might get out of control.

**Comment by aminomancer** [comment]
Alright I ended up letting the label wrap onto multiple lines, so try updating to v1.0.1. I also changed the aspect ratio to 16:9 fwiw

**Comment by aminomancer** [comment]
> very cool idea. is there any way TST compatibility could be added like with the old extension?

I don't know which extension you're talking about. I never used old Firefox extensions. But anyway, that would probably be a bit involved. Might even require rebuilding TST in a different format. Strictly speaking it is possible to use [JSActors](https://firefox-source-docs.mozilla.org/dom/ipc/jsactors.html) in the webext-browsers message manager group to send information from the content to the chrome window. But idk how much information will even be exposed to the child actor running in the sidebar. That is one of the reasons I made the [vertical tabs pane script](https://github.com/aminomancer/uc.css.js#vertical-tabs-pane), so that everything would be in the chrome window, in the parent process.

**Comment by aminomancer** [comment]
yeah there are trade-offs to everything

**Comment by kaos-55** [comment]
Awesome, it works and looks great, it's perfect.
Once again thank you very much for your work, you managed to bring back one of the features lost in Firefox when it removed its extensions in favor of webextensions.
I think this issue can be closed.
![thumb1](https://user-images.githubusercontent.com/86812371/153741198-9a797c6c-ba9c-4f03-8b35-c3132a835652.png)
