### ISSUE TITLE
Add option to search content on sidebar ("Edge-like" sidebar search feature)

### ISSUE THREAD

**Issue by ericpa06** [aminomancer/uc.css.js#38]
![image](https://user-images.githubusercontent.com/6937720/164872689-4e823707-79e6-4c69-87de-20660a466f08.png)
This would probably be too hard to do, but it might be interesting. I think it could be done through an extension, anyway: Edge and now Chrome, I think, have this "sidebar search" where you can search something and it gets displayed to you as sidebar. I think this option is honestly amazing, it's pretty useful because you can get a glimpse of a given content without having to leave the page, and it's shame it didn't get implement on Firefox yet.

The closet thing I could found was this extension here, but it's not exactly like a search bar, more like a "preview sidebar" or something, but I think a huge chunk of the code could maybe be used, but I have no idea what I'm talking.

https://addons.mozilla.org/en-US/firefox/addon/link-preview-sidebar/

**Comment by aminomancer** [comment]
Yeah this is more in the wheelhouse of an extension. It's not really practical to make sidebar documents with autoconfig, too much hackery since we're not allowed to use WebExtensions APIs. I would ask the developers of the addon you linked. You're right that it would be really easy to just change a few things in that addon to make it open a specific search URL instead of a link URL. But idk how the addon is constructed. I'm not sure whether the addon would be able to retrieve info about your default Firefox search engine, so it might have to be hard-coded with some search engines to pick from. So that's one respect in which it would be better if the feature was built into Firefox. But still, that's the kind of thing that would be feasible to build into Firefox but not so feasible to hack into Firefox via autoconfig. So it's not really practical for this repo, but you could post an enhancement request on bugzilla and if the proposal receives any support, I can look into working on it
