### ISSUE TITLE
Allow refreshing of URLs containing # on it by clicking in the URLBar and pressing enter

### ISSUE THREAD

**Issue by ericpa06** [aminomancer/uc.css.js#39]
This is apparently an old bug or issue, apparently, you can't refresh a URL that contains **#** somewhere in the in it, by just pressing enter (as it normally occurs). Here is an example:

**Pressing enter on enter on urlbar on a normal URL:**
![1650730384](https://user-images.githubusercontent.com/6937720/164914234-78fc7ea0-06a5-48f1-bd41-e80a82a80f1f.gif)
The page is reloaded.

**Pressing enter enter on a URL on containing **#** in it:**
![1650730422](https://user-images.githubusercontent.com/6937720/164914267-e26c0a3c-dea9-452e-af25-d8280e0d629d.gif)
Nothing happens.

Apparently someone propose they addressed this some years, but Mozilla didn't thought it was a bug or an issue. In my noob opinion, this doesn't seem to be an issue too hard to solved, but what I know? Anyway, just a suggestion.
https://bugzilla.mozilla.org/show_bug.cgi?id=778399

**Comment by aminomancer** [comment]
Well the hash mark separates the URL's path from the anchor string that jumps to the heading. It can't be fixed without breaking anchor navigation. Like my repo's readme? If you click the table of contents it would reload the entire page instead of jumping to the section you clicked. So yeah not really practical. Besides, if you really want to refresh you can just press Ctrl+R

**Comment by ericpa06** [comment]
![1650769983](https://user-images.githubusercontent.com/6937720/164954736-6be158ed-1edc-42d2-9268-5d1cebc1ad9c.gif)

I see... Just out of curiosity, I tested on Edge, and apparently it has that expected behavior I mentioned, how do they do that? Did they have to remove anchor navigation? Couldn't this same solution be implemented on Firefox? Anyway, thank you very much for your attention.

**Comment by aminomancer** [comment]
Not sure, I'm not familiar with the source code. Anchor navigation does work on Edge in terms of clicking links. But with the URL bar it's different from Firefox. In Firefox, I can type `https://github.com/aminomancer/uc.css.js` to load the page, then add `#details` and hit Enter, and it'll jump right to the section without reloading the page. Then I can change `#details` to `#fonts` and hit Enter and again, it'll jump to the section without reloading the page. In Edge, if you click a ref link it'll jump to the section without reloading the page. But any time you hit Enter it reloads the page, even if the URL leads to the same page. Whereas in Firefox, clicking a link and using the urlbar to type in the same link will produce the same results. So clicking links works the same in Edge and Firefox. But Firefox's urlbar has the same shortcut for jumping to sections without reloading the page that its link click handler has. Whereas Edge's urlbar doesn't have that shortcut.

Of course, the shortcut assumes that you want to navigate the page without reloading it. For people who want to reload the page on purpose (like you) this could seem like a bug. But I assume Mozilla haven't prioritized that since one can just hit Ctrl+R instead. Whereas if the feature is removed, there won't be any other way to jump to headings. [Here is part of the shortcut](https://searchfox.org/mozilla-central/rev/44527269dd96db7a3da81aafff33c84a031864c7/docshell/base/nsDocShell.cpp#9344-9347,9452-9460) I mentioned. Firefox basically handles navigation differently if the destination document is the same as the loaded document. And this is downstream of the urlbar and clicking, it's happening when a content viewer is created or navigation triggered, so it's gonna play out the same whether a link is clicked or input by text. Whereas in Edge, I'm sure the architectural situation must be analogous, but there probably is some higher level logic in the urlbar code that forces navigation.

I can think of ways it could be done in Firefox, generally involving changes to the docshell code. That's C++ though, not something a user can modify without rebuilding Firefox. I'm looking into a way to do this with a script. I think it would be best if it _only_ reloaded the page if the URL hasn't changed. That is, when the current browser URL is the same as the string in the urlbar. If you type anything different then it should behave as it currently does. But if the URL hasn't changed at all then it's safe to assume we're not trying to navigate, we're just trying to refresh the page. So at that point we can hand off control to a new method that forces a reload.

**Comment by aminomancer** [comment]
I posted a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1766145) concerning this issue if you want to follow the developments. I'm working on turning the patch into an autoconfig script, in any case.

**Comment by aminomancer** [comment]
Alright [try this script](https://github.com/aminomancer/uc.css.js#hit-enter-in-urlbar-to-refresh) and lmk if it works for you.

**Comment by ericpa06** [comment]
Thank you very much for implementing this script!!!
