### ISSUE TITLE
Make findbar highlighted text to always use the same color, no matter the background color of the page in question?

### ISSUE THREAD

**Issue by ericpa06** [aminomancer/uc.css.js#47]
![image](https://user-images.githubusercontent.com/6937720/172952641-b04d4195-807e-42bc-aa12-d1dfd0f48013.png)
So, this is a little hard to explain, basically depending on the background of the page you are in, the highlighted color of the text _(as well as the color of text you are highlighting in itself)_, when you use the findbar changes, it sorta inverters on darker backgrounds. This thread on **FirefoxCSS** better explained what I'm talking about:
https://old.reddit.com/r/FirefoxCSS/comments/mfw002/keeping_uitexthighlightbackground_consistent_on/gspslgv/

I was wondering if there is any way to make the highlighted text cohesive and to always use to the same color no matter what, like it works on other browsers? As always, thank you very much and sorry to bother.

**Comment by aminomancer** [comment]
Selection highlighters like the findbar's are implemented in C++ so autoconfig scripts can't do anything to change their behavior. The highlighter is performing calculations to find the contrast between the highlight background color and the background color of the content it's being drawn on. So that's why it's inverting the colors. Anyway, the highlighters use the look-and-feel color system, which can be [configured by preferences](https://searchfox.org/mozilla-central/rev/552bfc6334b797d92fb2ce8e93a6ace5f47cd56d/widget/nsXPLookAndFeel.cpp#204-220). If you look in [my readme](https://github.com/aminomancer/uc.css.js#recommended-settings) there's a list of recommended settings. It includes selection color settings, the ones that start with `ui`. If you configure them correctly, the colors will never invert.

It's hard to explain how it works, but it seems to compare the colors as background/foreground layers. So, the way I've done this is to use a color of medium brightness for all the background prefs and white for all the foreground prefs. That way I always get the same colors. However, I'm not sure if you can replace white with black and still get that consistent behavior. If I'm remembering correctly, I think if you use black on ~50% brightness, there's a potential for it to basically flip the layers. I could be wrong though, I haven't looked closely at the source code for this. But I prefer white text anyway, since I use dark reader.

**Comment by aminomancer** [comment]
You can offer your feedback in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1687074) though

**Comment by ericpa06** [comment]
Thanks..
