### ISSUE TITLE
Hey i have tried the min script it's broken ...

### ISSUE THREAD

**Issue by mohith01** [aminomancer/uc.css.js#5]
i have used custom userChrome and userContent js with the instructions u gave. So everything else apart from that was downloaded. These are my userChrome css and userContent js..  Replace the text files with .css and this is my first time using firefox css.. So pls help :)

[userContent.txt](https://github.com/aminomancer/uc.css.js/files/6370329/userContent.txt)

[userChrome.txt](https://github.com/aminomancer/uc.css.js/files/6370328/userChrome.txt)

**Comment by aminomancer** [comment]
the script isn't broken at all, you're trying to use it with a stylesheet that is clearly incompatible with it. your problem is line 411 of userChrome, which gives the tabs an absolute position.

```
#TabsToolbar {
  position: absolute !important;
  display:block !important;
  bottom: 0 !important;
  width: 100vw !important;
}
```

the whole purpose of the script is to make the tabs bar and the navbar occupy the same position. you can't have the tabs on the bottom of the window with this script, since then you'd need to have the navbar on bottom too, which would mean the urlbar would be on the bottom, which in turn would mean the urlbar results would be completely flowing off the bottom of your monitor.

what you're seeing is the tabs on bottom and the navbar still on top. which is exactly how your stylesheet looks without my script. the script isn't magic, it can't read your stylesheet and magically adapt to do whatever you want it to. all it can do is what I tell it, and my instructions expect a layout that at least vaguely resembles the vanilla firefox UI.

**Comment by mohith01** [comment]
damnn bro u r too harsh..but yeah I deserved it ... do I need to download like the entire folder and sort it ? like I want mainly the min functionality. what and all shd I download?

**Comment by aminomancer** [comment]
you don't need anything but the script, it's a standalone thing. you just can't have rules in your stylesheet that conflict with the script

**Comment by mohith01** [comment]
okay I will try and let u k in couple of minutes

**Comment by mohith01** [comment]
Hey i have tried it... Can u please send me your whole folder tree structure..it will give me a better idea of how u have arranged.. I have cloned your repo and used it like below without changing any of the files 
![image](https://user-images.githubusercontent.com/42903811/116536900-283cc780-a903-11eb-949e-99e171ebb677.png)
And I end up with something like this
![image](https://user-images.githubusercontent.com/42903811/116536985-43a7d280-a903-11eb-8085-c27a44e11e38.png)
I am sorry for irritating you but your videos look too cool and I really want to have a firefox setup like that and idk any basics abt it...

**Comment by aminomancer** [comment]
the folder structure is correct. what firefox version are you doing this on? what script loader are you using? show me the directory structure of your firefox install folder. what userChrome and userContent.css files are you using? you can't use my userChrome.au.css and userChrome.as.css without the rest of my stylesheets. like, they aren't modular components, they are part of the theme. it's not intended to be combined with other themes, you should either not use any of my CSS files, or use all of them and only them. (unless you know what you're doing, of course)

**Comment by mohith01** [comment]
My firefox version is Mozilla Firefox 88.0 and  this is my tree structure for firefox install folder
![image](https://user-images.githubusercontent.com/42903811/116661814-a1472800-a9b2-11eb-8a0c-2d20083040e4.png)
I am using  fx auto-config  script loader.. and I have changed my tree structure
![image](https://user-images.githubusercontent.com/42903811/116662193-1581cb80-a9b3-11eb-8062-ab3c766fd806.png)
Ryt now in my userChrome.css I have removed most of the css. and I have changed my chrome.manifest.. The _as_css.uc.js files I have used are the same files which I directly got from fx-autoconfig. I have sent all the files as a zip folder below. Please check and let me k..
[uc.js.zip](https://github.com/aminomancer/uc.css.js/files/6403581/uc.js.zip)

**Comment by aminomancer** [comment]
You don't need the `userChrome_as_css.uc.js` or `userChrome_as_css_module.uc.js` since you don't have any agent or author sheets. Those are only used for loading `userChrome.as.css` which you don't need.

I didn't know you were on linux. I've only tested the script on windows 10. I've heard it works on macOS too, but no idea about linux. The fact that your window says "undefined" at the top suggests something is totally broken. What happens when you delete the script `minBrowserNavbar.uc.js` but leave all the other stuff, including fx-autoconfig? Do any other scripts work for you? I don't really have much to go on here since I don't have a linux system to test on.

The script should work on firefox 88, but what update branch? Stable, ESR? Beta? Nightly? Developer Edition? All I can really say is there's probably some incompatibility with linux, or maybe your profile, or your particular Firefox installation. If you're really committed to getting this script working, you should try going to `about:profiles` and creating a new profile and copying your chrome folder over to it. Then try testing on the brand new profile. If it works in there, then you know your main profile probably has a setting in `about:config` that's messing something up. Did you check the preferences table at the top of my readme? On the main page of the repo, all the way at the top there's an expandable list of recommended preferences.

I can't see anything in the script that would cause anything like this. I tested the whole package of files you sent me and it worked fine for me. So it must be either 1) your profile, 2) your firefox install, or 3) your operating system itself. I did update a few things just now, animated the reload button and adjusted the padding for the proton layout, but nothing that seems to be related to your issue.

**Comment by mohith01** [comment]
My firefox version branch is stable one . I have tested it on a new profile as u said it works..I think there's a problem on about:config of my default profile.. will have to hack the error up tomorrow....Apart from the updates u did to the file I think the link suggestions icons are also broken..Thanks a lot for your help..Sorry if I was annoying


https://user-images.githubusercontent.com/42903811/116729646-07f53180-aa05-11eb-9db7-881c6f6d6d17.mp4

**Comment by aminomancer** [comment]
the icons are working fine. if you're gonna use my `chrome.manifest` file, then you need to download the entire `resources` folder from the repo and put it in your chrome folder. the `chrome.manifest` file redirects the URLs of a bunch of icons to files in the `resources` folder, so if you don't have the folder, the links will be dead.

**Comment by mohith01** [comment]
Hmm yeahh i will do that.. Thanks a lott
