### ISSUE TITLE
[BUG] Private Tabs script not working in Firefox 104.0.2

### ISSUE THREAD

**Issue by kaos-55** [aminomancer/uc.css.js#53]
**Describe the bug**
Hi @aminomancer Again bothering you
I was testing various scripts from the repository and decided to try private tabs, however apparently the script does not work in Firefox 104.0.2. 

**To Reproduce**
1. Firefox clean install
2. Install Fx-Autoconfig MrOtherGuy (lastest version)
3. Install privateTabs.uc.js from the repository
4. Restart Firefox

**Expected behavior**
The private tab icon is displayed in the toolbar but does not appear.

**Desktop:**
 - OS: Windows 10
 - Firefox update channel: Stable
 - Version: 104.0.2

**Additional context**
It is worth mentioning that the other scripts work correctly

**Comment by aminomancer** [comment]
Like the readme says, none of the scripts on this repo support release builds. Some of them will incidentally work but they're not designed to, and aren't tested on release. When a script stops working in Nightly because something has changed, I update the script immediately. So whatever was necessary to make it work on the new Nightly version is probably going to make it stop working on versions prior to that.

But I guess you could try an [old version](https://github.com/aminomancer/uc.css.js/blob/4011ad75572aede3e383b5d855c62b854112920d/JS/privateTabs.uc.js) of the script

**Comment by kaos-55** [comment]
Thank you for your reply, now i understand. For not having read the readme 🤦🏿‍♂️

However, I just downloaded the latest version of Nightly to test the script and it doesn't work either, the private tabs icon doesn't appear and the keyboard shortcut doesn't work either.

**Comment by aminomancer** [comment]
Okay, thanks for the report. I'll take a look at it over the weekend

**Comment by kaos-55** [comment]
Thanks.
Finally i just tested an older version of the script, specifically 1.2 and it works. Apparently the changes introduced in version 1.2.1 broke the script.

**Comment by aminomancer** [comment]
Try version 1.2.2, that should work now

**Comment by kaos-55** [comment]
Thank you it is fixed, now it works in Nightly. 👍
