### ISSUE TITLE
Firefox 108 breaking "Tab Thumbnail ToolTip" script on pages with page title too long?

### ISSUE THREAD

**Issue by ericpa06** [aminomancer/uc.css.js#62]
Hello, I just updated Firefox Developer to the 108 version, and Mozilla seems to have made some change that break the script.  Especially when the page title is too long. 
![image_215](https://user-images.githubusercontent.com/6937720/202231721-4aa05b11-aa4d-49dd-a9bb-2708e77bae42.png)

It seems to be some issue with **#tabThumbBox** part, I tried to fix by tweaking around with CSS, but hadn't have much success.
It could something due to my setup, but I think it is worth a look. Thank you very much for your attention

**Update:** Forget what I said about "tabThumbBox",  I think the problem is the model "Max label character limit" isn't working, so it doesn't crop the page title when seeing the thumbnail,

**Comment by kaos-55** [comment]
I can confirm this, not only the script is broken in the developer version but also in nightly. Apparently a change in Firefox makes that the "Max label character limit" is not respected, also the thumbnail of the tab is out of the canvas.
![github-isssue](https://user-images.githubusercontent.com/86812371/203294719-48a40883-ab8a-4066-9bb7-01d1c5640156.png)

**Comment by aminomancer** [comment]
It's likely because of the [xul modern flexbox emulation](https://bugzilla.mozilla.org/show_bug.cgi?id=1033225) improvements. The change has affected several of my scripts unfortunately. I've been pretty busy, but I will get around to it eventually.

**Comment by kaos-55** [comment]
After several months of trying to fix the script myself, through trial and error, I think I was able to fix the script.

Before the fix:
![no-fixed](https://user-images.githubusercontent.com/86812371/220363644-49efa693-080b-4f10-9926-1c5bf65f7c51.png)

After the fix:
![fixed](https://user-images.githubusercontent.com/86812371/220363699-769a5857-bcfa-458a-a43c-3e51e2285a98.png)

Although I still don't know how to fix the ellipsis, since it changes me to this character "&".
I fixed it temporarily by using three dots.
I leave this in case anyone is interested.

**Comment by aminomancer** [comment]
Thanks, I fixed it. Sorry, I didn't realize turning the overflow character setting into a pref would change its encoding.

I fixed the layout issue too. It is resolved by putting the label in another container and constraining the container's width.
