### ISSUE TITLE
[BUG]clearDownloadsButton.uc.js console error

### ISSUE THREAD

**Issue by hansemn** [aminomancer/uc.css.js#78]
**Describe the bug**
clearDownloadsButton.uc.js causes an error in browser console

**To Reproduce**
1. Install clearDownloadsButton.uc.js 1.4.2
2. run Firefox
3. open browser console
4. error: Uncaught ReferenceError: gBrowserInit is not defined

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Firefox update channel: [should be Nightly] Release, soon ESR
 - Version: 115.03
 - Build ID: 20230726201356

**Additional context**

The scripts works great regardless, just thought I'd mention the error in browser console.

It's not tested in Nightly, which I can't use anymore due to a recently unsupported OS, but that bit of code (gBrowserInit )has been in the script for a while, and _might_ in general be deprecated.

Thanks very much for your contributions, much appreciated!

![error](https://github.com/aminomancer/uc.css.js/assets/124502482/89f6a792-cb10-41c9-99f0-847ca988f860)

**Comment by aminomancer** [comment]
Just FYI, the scripts on this repo only support Nightly, sorry :/ I would recommend downloading the [repo from before June](https://github.com/aminomancer/uc.css.js/archive/43b13c339d23c83f903d9a1eec563fade1ea197f.zip), so you get the scripts that were compatible with 115. Going forward, you probably won't be able to use new and updated scripts here, as they are all based on 118+.

You should also do the same with your script loader. I can only attest to my scripts' compatibility with fx-autoconfig. So, [here's fx-autoconfig](https://github.com/MrOtherGuy/fx-autoconfig/archive/b0312502f970e9a72184fe9b238d8e0feaca2e3d.zip) at the time of 115.

Anyway, `gBrowserInit` is [not deprecated](https://searchfox.org/mozilla-central/rev/4044c34031d035fadb588143297ba5421419d44b/browser/base/content/browser.js#1443).

It sounds like your issue is with your script loader. 1.4.2 of the script should still work in 115. If gBrowserInit doesn't exist when the script executes, it means your script loader is loading scripts too late.

Judging by the console log (`Firefox.app/Contents/Resources/userChromeJS/utilties.js`), you're not using a compatible script loader. So, you should look to your script loader for problems, or switch to fx-autoconfig.

**Comment by hansemn** [comment]
Thanks a lot for the reply, I'll look into my loader.

Your script is still working fine though, so no sweat. ;)

**Comment by aminomancer** [comment]
Oh that's weird, from the console error I would have assumed the whole script broke
