### ISSUE TITLE
Extension panel broken with minbrowser navbar

### ISSUE THREAD

**Issue by uvera** [aminomancer/uc.css.js#8]
When you open extension panel UI, URL bar gets closed so you can't mouse click on anything within that extension popup (broken for every extension of course), clicks get passed through the panel popup to current page.

Only workaround is holding Alt+D for clicks to get passed to the popup

Running latest FF nightly on Linux with upstream userChrome changes.

![image](https://user-images.githubusercontent.com/5598427/124327739-e2f17c00-db77-11eb-9dd4-0bcaae41690a.png)

**Comment by aminomancer** [comment]
thanks for the report. unfortunately that script is very old and just something I made by request a long time ago. I haven't tested it in months and it already had problems even back when I made it. I think in retrospect I should have approached the script an entirely different way. I have learned a lot since then and realized how folly it was. it's sort of a house of cards, so I think it'd be better to tear the whole thing down and rebuild it on a sturdier foundation than to try and patch the holes in such a broken mess. I'll probably look into that soon now that I know there are people who actually want to use it, but at the moment I've been a little preoccupied working on vertical tabs implementations.
